#### Numpy

In [1]:
!pip install numpy # pip is python package manager

In [3]:
import numpy as np

In [4]:
numbers = np.array([3,5,6,7,8,9]) # takes a list of numbers and converts it to a numpy array

In [5]:
numbers

array([3, 5, 6, 7, 8, 9])

In [6]:
scores = np.array((30, 40, 50, 20))

In [7]:
scores

array([30, 40, 50, 20])

In [8]:
type(scores)

numpy.ndarray

In [9]:
student_ages = np.array([34, '23', 35])

In [11]:
student_ages # dtype represents the data type of the items in the array

array(['34', '23', '35'], dtype='<U11')

In [12]:
weights = np.array([34.0, 23.5, 45.9], dtype='float32')

In [13]:
weights

array([34. , 23.5, 45.9], dtype=float32)

In [14]:
heights = np.array([34.6, 23.4, 45.7])

In [15]:
heights

array([34.6, 23.4, 45.7])

In [16]:
heights.dtype

dtype('float64')

In [18]:
heights.ndim

1

In [19]:
array_2dim = np.array([[3, 5, 7], [5, 7, 9]])

In [20]:
array_2dim

array([[3, 5, 7],
       [5, 7, 9]])

In [22]:
array_2dim.ndim

2

In [23]:
array_2dim.shape

(2, 3)

In [24]:
arr_2 = np.array([[2,5,6,7], [4,5,6,7], [5,6,7,8]])

In [25]:
arr_2.shape

(3, 4)

In [26]:
# Exercise : Create a 2 dim array of shape 4 by 4

arr_3 = np.array([[2,5,6,7], [4,5,6,7], [5,6,7,8], [3,4,5,6]])

In [27]:
arr_3.shape

(4, 4)

In [28]:
arr_3.size

16

In [29]:
arr_4 = arr_3.reshape(2,8)

In [30]:
arr_4

array([[2, 5, 6, 7, 4, 5, 6, 7],
       [5, 6, 7, 8, 3, 4, 5, 6]])

In [31]:
arr_4.shape

(2, 8)

In [41]:
scores = np.array([40, '30', 20, '30', '60'])

In [42]:
scores.dtype

dtype('<U11')

In [38]:
# type casting 

scores = scores.astype('int')

In [39]:
scores

array([40, 30, 20, 30, 60])

In [40]:
scores.dtype

dtype('int32')

#### Indexing and Slicing

In [43]:
fruits = np.array(['mango', 'orange', 'guava', 'pineapple'])

In [44]:
fruits[0]

'mango'

In [45]:
fruits[-2]

'guava'

In [47]:
fruits[0:3]

array(['mango', 'orange', 'guava'], dtype='<U9')

In [50]:
scores = np.array([[3,4,5], [6,8,1], [2, 12, 14]])

In [51]:
scores

array([[ 3,  4,  5],
       [ 6,  8,  1],
       [ 2, 12, 14]])

In [52]:
scores[0,0]

3

In [53]:
scores[1,1]

8

In [54]:
scores[2,2]

14

In [55]:
scores[-2,-1]

1

In [56]:
scores[0:2,:]

array([[3, 4, 5],
       [6, 8, 1]])

In [58]:
scores[0:2,1:3]

array([[4, 5],
       [8, 1]])

In [62]:
scores[1:-1]

array([[6, 8, 1]])

In [60]:
scores[1:-1]

array([[6, 8, 1]])

#### Vectorized operations

In [63]:
scores = np.array([10, 12, 23, 45, 10])

In [64]:
scores * 10

array([100, 120, 230, 450, 100])

In [65]:
scores - 5

array([ 5,  7, 18, 40,  5])

#### Pandas


`Data Structures`

- Series : 1 dimensional data structure that model a column

- DataFrame : 2 dimensional data structure that models a table - rows and columns

In [69]:
import pandas as pd

C:\Users\aaginam\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [70]:
names = pd.Series(['Tolu', 'John', 'Femi', 'Rhoda'])

In [71]:
names

0     Tolu
1     John
2     Femi
3    Rhoda
dtype: object

In [80]:
names[3]

'Rhoda'

In [83]:
scores = pd.Series([20, 30, 30, 40], index = ['a', 'b', 'c', 'd'], dtype='int64')

In [84]:
scores

a    20
b    30
c    30
d    40
dtype: int64

In [85]:
scores * 4

a     80
b    120
c    120
d    160
dtype: int64

In [76]:
scores['b']

30

In [77]:
df = pd.DataFrame({
    'Names' : ['Tolu', 'Mary', 'Janet', 'Yinka'],
    'Scores' : [45, 34, 23, 67]
})

In [78]:
df

Names  Scores
0   Tolu      45
1   Mary      34
2  Janet      23
3  Yinka      67

In [79]:
type(df)

pandas.core.frame.DataFrame